# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3345c8d3681213be73af1ab8ed24ed3582313158f0e8a49089847df5cec5fe3642a248efe6aa2ffe21b6948d5d81cc1be6b1cecaeab0243da2a6653c404429a4

test:
  secret_key_base: 3dc065a1b2e3110de67537ac63436e370b80bad617e2b725f3e1a21e95307441bb65b783e72b5776bec962a7e81474857b9ac8eecda1ca8eee8a9cfb0daafa41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
